fminunc_options = optimoptions(@fminunc,'Display','iter',...
                               'Algorithm','quasi-newton',...
                               'HessUpdate','bfgs',...
                               'MaxFunctionEvaluations',50000,...
                               'OptimalityTolerance',1e-10,...
                               'StepTolerance',1e-10);

fminsearch_options = optimset('Display','iter');